export const ADD_TASK = 'ADD_TASK';
export const SET_PENDING_TASKS_LIST = 'SET_PENDING_TASKS_LIST';
export const SET_PROCESSING_TASKS_LIST = 'SET_PROCESSING_TASKS_LIST';
export const SET_DONE_TASKS_LIST = 'SET_DONE_TASKS_LIST';
